const Routes = {
    home: 'Home',
    dashboard: 'Dashboard',
    category: 'Category',
    search: 'Search',
    notification: 'Notification',
    setting: 'Setting',
    access: 'Access',
    login: 'Login',
    register: 'Register',
    updateDetails: 'UpdateDetails',
    createPost: 'CreatePost',
    editPost: 'EditPost',
    createApplication: 'CreateApplication',
    applicationDetails: 'ApplicationDetails',
    editApplication: 'EditApplication',
    applicationList: 'ApplicationList',
    myPost: 'MyPost',
    editDetails: 'EditDetails',
    createReview: 'CreateReview',
    editReview: 'EditReview',
    singleCategory: 'SingleCategory',
    profile: 'Profile',
    appChat: 'AppChat',
    globalChat: 'GlobalChat',
    userChat: 'UserChat',
    postDetails: 'PostDetails',
    tagChat: 'TagChat',
    tagList: 'TagList',
    addTag: 'AddTag',
    editTag: 'EditTag',
    myTag: 'MyTag',
    myReview: 'MyReview',
    myBooking: 'MyBooking',
    createBooking: 'CreateBooking',
    editBooking: 'EditBooking',
}

export default Routes;